### ISSUE TITLE
Is this project still supported?

### ISSUE THREAD

**Issue by Radagan** [PerfectlySoft/Perfect-Mosquitto#1]
I'm looking for the best MQTT client for Swift on Linux and found this one right here in Perfect! Which, would be perfect, but it's lagging behind Swift 4.2 and I'm having difficulty getting it to build. 

Should I try and fix it or is this abandoned? Is there a better route for MQTT for Swift on Linux? I'm looking to connect with Google IoT Core.

**Comment by RockfordWei** [comment]
Yes, please check out the master release 3.1.0
