### ISSUE TITLE
Why is manually creating package configuration file needed?

### ISSUE THREAD

**Issue by wlisac** [PerfectlySoft/Perfect-Mosquitto#4]
Hi there,

I'm trying to understand why manually creating the PC file is needed and if there is a way to avoid it.

https://github.com/PerfectlySoft/Perfect-Mosquitto#pc-file

Having this extra step adds some (minor) overhead compared to just being able to do `swift build` directly.

Thanks for this library – it has been very helpful. 🙂

**Comment by wlisac** [comment]
I looked at [Perfect-Kafka](https://github.com/PerfectlySoft/Perfect-Kafka), which is wrapping librdkafka. This doesn't require manually creating a PC file.

It looks like librdkafka automatically creates the necessary PC files during brew install. Maybe the solution is to see if we can get mosquitto to do the same.

**Comment by wlisac** [comment]
I did a little more digging and it looks like mosquitto installs a default pkgconfig file of `libmosquitto.pc`.

https://github.com/eclipse/mosquitto/search?q=libmosquitto.pc&unscoped_q=libmosquitto.pc

I think the change for this could be really simple – I tested this fix on macOS and Debian: https://github.com/PerfectlySoft/Perfect-Mosquitto/commit/e8c821115d540fa3dc1032152c3dc4e2e86bf12e

I'd like to test a few more configurations, but I plan to open a PR for this soon.

**Comment by RockfordWei** [comment]
Thank you. I just added a bit instructions on post `brew upgrade mosquito`.
